
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    env_file:
      - frontend/.env.development
    networks:
      - network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-backend
    volumes:
      - ./backend:/app
      - ./backend/pb_data:/app/pb_data
      - ./backend/migrations:/app/migrations
      - ./backend/sf_logs:/app/sf_logs
    ports:
      - "8090:8090"
    networks:
      - network
    depends_on:
      - vm1
      - vm2

  vm1:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-vm
    networks:
      - network

  vm2:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-vm
    networks:
      - network

networks:
  network:
    driver: bridge
